import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import Head from "next/head";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <Head>
          <>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            />
            {/* Favicon icon*/}
            <link
              rel="shortcut icon"
              type="image/png"
              href="./images/logos/favicon.png"
            />
            <link
              href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap"
              rel="stylesheet"
            />
            <link
              rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.44.0/tabler-icons.min.css"
            />
            {/* Core Css */}
            <link rel="stylesheet" href="./css/theme.css" />
            <title>Modernize TailwindCSS HTML Admin Template</title>
          </>
        </Head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex">
            <Sidebar />
            <div className="flex flex-col w-full min-h-full">
              <Header />
              {children}
            </div>
          </div>
        </body>
      </html>

      <Script src="./libs/jquery/dist/jquery.min.js"></Script>
      <Script src="./libs/simplebar/dist/simplebar.min.js"></Script>
      <Script src="./libs/iconify-icon/dist/iconify-icon.min.js"></Script>
      <Script src="./libs/@preline/dropdown/index.js"></Script>
      <Script src="./libs/@preline/overlay/index.js"></Script>
      <Script src="./js/sidebarmenu.js"></Script>
    </>
  );
}
